[package]
name = "dlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
error-chain = "0.12.4"
futures = "0.3.28"
reqwest = { version = "0.11.18", features = ['blocking'] }
tokio = { version = "1.29.1", features = ["full"] }
